<#include "../../include/imports.ftl">
<#include "../catalog-macros.ftl">
<@hst.setBundle basename="SearchPage,ProductToolbar,AddToCartBar,eshop,ProductConfigurator,StandardStockedItems,SparesAccessories"/>
<#macro spareAccessoryList componentId sparesAccessories showPagination=true>
    <div id="${componentId}" class="spares-accessories-container">
        <div class="row pagination_showing mb-2 ${showPagination?then('', 'hidden')}">
            <div class="col-6 text-bold">
                <!--  --->
                <@fmt.message key="search.searchresult.paging.showing"/>
                <span class="js-search-init-page-number">?</span>
                <!--   --->
                <@fmt.message key="search.searchresult.paging.to"/>
                <span class="js-search-finish-page-number">?</span>
                <!--   --->
                <@fmt.message key="search.searchresult.paging.of"/>
                <span class="js-search-total">?</span>
                <!--   --->
                <@fmt.message key="search.searchresult.paging.entries"/>
            </div>
            <div class="col-6 text-bold text-right d-none d-sm-block pr-xl-4">
                <!--   --->
                <@fmt.message key="search.searchresult.paging.display"/> <a class="active changelen" data-page-size="10" href="#">10</a> | <a  class="changelen" data-page-size="20" href="#">20</a> | <a  class="changelen" data-page-size="50" href="#">50</a> | <a  class="changelen" data-page-size="100" href="#">100</a>
            </div>
        </div>

        <div class="row mb-2 d-none d-lg-flex">
            <div class="col-lg-3 col-sm-3 col-3 sub-title" id = "partNumberLbl" ><@fmt.message key="sparesaccessories.partnumber" /></div>
            <div class="col-lg-7 col-sm-7 col-7 sub-title" id = "productDescriptionLbl" ><@fmt.message key="sparesaccessories.productdescription"/></div>
            <div class="col-lg-2 col-sm-2 col-2 sub-title text-center d-block d-sm-none">
                <a href="javascript:void(0);" rel="tooltip" data-toggle="tooltip" data-placement="top" title="<@fmt.message key="sparesaccessories.additionalinformation"/>">
                    <i class="icon icon-info-circled"></i>
                </a>
            </div>
            <div class="col-lg-2 col-sm-2 col-2 sub-title text-center d-none d-sm-block" id = "additionalinformationLbl" ><@fmt.message key="sparesaccessories.additionalinformation"/></div>
        </div>
        <div class="spares-accessories-result-container">
            <!-- Generated by JS -->
        </div>
    </div>

    <script>
        window.smc = window.smc || {};
        window.smc.productSparesAccessoryList = [];
        var pnLbl = $("#partNumberLbl").text();
        var descriptionLbl = $("#productDescriptionLbl").text();
        var additionalInfoLbl = $("#additionalinformationLbl").text();
        <#list sparesAccessories as spareAccessory>
        window.smc.productSparesAccessoryList.push({
            partNumberLbl : '${pnLbl}',
            partNumber: '${spareAccessory.getPartNumber()}',
            description: "${spareAccessory.getDescription()}",//[SMCD-370]
            additionalInformation: "${spareAccessory.getAditionalInformation()}",//[SMCD-370]
            imageUrl: '${spareAccessory.getImageUrl()}'
        });
        </#list>
    </script>

    <#if !showPagination>
        <script>
            $(function () {
                var spare = new window.smc.SparesAccessories({
                    id: '${componentId}',
                    container: $('#${componentId}'),
                    items: window.smc.productSparesAccessoryList,
                    paginateResults: ${showPagination?c}
                });
                spare.init();
                $(".partNumberLabel").each(function(){
                    $(this).attr("data-field-title",$("#partNumberLbl").text());
                });
                $(".productDescriptionLabel").each(function(){
                    $(this).attr("data-field-title",$("#productDescriptionLbl").text());
                });
                $(".additionalinformationLabel").each(function(){
                    $(this).attr("data-field-title",$("#additionalinformationLbl").text());
                });
            });
        </script>
    </#if>

    <script>
        $(function () {
            $('[rel="tooltip"]').tooltip();
        });
    </script>
</#macro>

<script id="spareAccessoryItemTemplate" type="text/template">
    <div class="row spare-accessory-item mb-10 mb-md-0">
        <div class="col-lg-3 col-12 partNumberLabel" data-field-title="" >
            <label for="{{componentId}}_{{partNumber}}_{{index}}" class="smc-checkbox">
                <input id="{{componentId}}_{{partNumber}}_{{index}}" type="checkbox" class="spare-accessory-item-partnumber" value="{{partNumber}}"/>
                <span class="smc-checkbox__label">{{partNumber}}</span>
            </label>
        </div>
        <div class="col-lg-7 col-12 productDescriptionLabel" data-field-title="" >
            <div class="spare-accesory-item__description">
                {{description}}
            </div>
        </div>

        <div class="col-lg-2 col-12 additionalinformationLabel" data-field-title="">
            <div class="additionalinformationDataContainer">
                <div class="spares-accesory-item__additional-info {{withImage}}">
                    <span class="image-icon">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
                    <div class="image-thumbnail">
                        <div class="popover fade show bs-popover-left" role="tooltip" x-placement="left">
                            <div class="arrow" style="top: 16px;"></div>
                            <h3 class="popover-header"></h3>
                            <div class="popover-body"><img src="{{imageUrl}}" style="max-height: 80px;" /></div>
                        </div>
                    </div>
                </div>
                <div class="text-center {{withoutImage}}">-</div>
                <#if ( isAccessoryDetailsModalEnabled?? && isAccessoryDetailsModalEnabled == true)  >
                    <div id = "accesoriesModal_{{componentId}}_{{partNumber}}_{{index}}_ssi" class="spares-accesory-item__actions">
                        <div class="product-toolbar-item accessory-modal-container hidden">
                            <a href="javascript:void(0);" data-toggle="tooltip" data-placement="bottom"
                               class="show-accessory-modal iconed-text series-ssi-cad-download"
                               title="<@fmt.message key="productConfigurator.showDetails"/>">
                                <div class="pl-2 product-toolbar-menu-item"><i class="icon-accessory-modal"></i></div>
                                <i class="loading-container-js"></i>
                            </a>
                        </div>
                    </div>
                </#if>
            </div>
        </div>
    </div>
</script>
