<#include "../../../include/imports.ftl">
<#include "../../catalog-macros.ftl">

<#macro productRelatedList componentId relatedProducts>
    <div id="${componentId}" class="spares-accessories-container">

        <div class="row mb-2 d-none d-lg-flex d-none d-lg-flex">
            <div class="col-lg-3 col-sm-3 col-3 sub-title"><@fmt.message key="standardstockeditems.partnumber" /></div>
            <div class="col-lg-7 col-sm-7 col-7 sub-title"><@fmt.message key="standardstockeditems.productdescription"/></div>
            <div class="col-lg-2 col-sm-2 col-2 sub-title text-center d-block d-sm-none">
                <a href="javascript:void(0);" rel="tooltip" data-toggle="tooltip" data-placement="top" title="<@fmt.message key="standardstockeditems.additionalinformation"/>">
                    <i class="icon icon-info-circled"></i>
                </a>
            </div>
            <div class="col-lg-2 col-sm-2 col-2 sub-title text-center d-none d-sm-block"><@fmt.message key="standardstockeditems.additionalinformation"/></div>
        </div>
        <div id="${componentId}-related-products-result-container">
            <!-- Generated by JS -->
        </div>
    </div>

    <script>
        window.smc = window.smc || {};
        window.smc.relatedProductList = [];
        <#list relatedProducts as relatedProduct>
        window.smc.relatedProductList.push({
            partNumber: '${relatedProduct.getPartNumber()}',
            description: '${relatedProduct.getDescription()}',
            imageUrl: '${relatedProduct.getImageUrl()}'
        });
        </#list>
    </script>


    <script>
        $(function () {
            var relatedProduct = new window.smc.RelatedProducts({
                id: '${componentId}',
                container: $('#${componentId}-related-products-result-container'),
                items: window.smc.relatedProductList
            });
            relatedProduct.init();
            $(".partNumberLabel").each(function(){
                $(this).attr("data-field-title",$("#partNumberLbl").text());
            });
            $(".productDescriptionLabel").each(function(){
                $(this).attr("data-field-title",$("#productDescriptionLbl").text());
            });
            $(".additionalinformationLabel").each(function(){
                $(this).attr("data-field-title",$("#additionalinformationLbl").text());
            });
        });
    </script>

</#macro>

<script id="relatedProductItemTemplate" type="text/template">
    <div class="row spare-accessory-item mb-10 mb-md-0">
        <div class="col-lg-3 col-12  partNumberLabel"  data-field-title="">
            <label for="{{componentId}}_{{partNumber}}_{{index}}" class="smc-checkbox">
                <input id="{{componentId}}_{{partNumber}}_{{index}}" type="checkbox" class="related-product-item-partnumber" value="{{partNumber}}">
                <span class="smc-checkbox__label">{{partNumber}}</span>
            </label>
        </div>
        <div class="col-lg-7 col-12 productDescriptionLabel"  data-field-title="">{{description}}</div>
        <div class="col-lg-2 col-12 additionalinformationLabel"  data-field-title="">
            <div class="additionalinformationDataContainer">
                <div class="spares-accesory-item__additional-info {{withImage}}">
                    <span class="image-icon">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
                    <div class="image-thumbnail">
                        <div class="popover fade show bs-popover-left" role="tooltip" x-placement="left">
                            <div class="arrow" style="top: 16px;"></div>
                            <h3 class="popover-header"></h3>
                            <div class="popover-body"><img src="{{imageUrl}}" style="max-height: 80px;" /></div>
                        </div>
                    </div>
                </div>
                <div class="text-center {{withoutImage}}">-</div>
                <#if ( isAccessoryDetailsModalEnabled?? && isAccessoryDetailsModalEnabled == true)  >
                    <div id = "accesoriesModal_{{componentId}}_{{partNumber}}_{{index}}_ssi" class="spares-accesory-item__actions">
                        <div class="product-toolbar-item accessory-modal-container hidden">
                            <a href="javascript:void(0);" data-toggle="tooltip" data-placement="bottom"
                               class="show-accessory-modal iconed-text series-ssi-cad-download"
                               title="<@fmt.message key="productConfigurator.showDetails"/>">
                                <div class="pl-2 product-toolbar-menu-item"><i class="icon-accessory-modal"></i></div>
                                <i class="loading-container-js"></i>
                            </a>
                        </div>
                    </div>
                </#if>
            </div>
        </div>
    </div>
</script>
